### PR TITLE
included countFromFieldSum to sum up numbers

### PR DESCRIPTION
**Pull request by dohomi**
Hi @tmeasday 

I added the option `countFromFieldSum`into this project. It counts a column which is based on numbers, accordingly to countFromFieldLength.

I added the basic test for this feature and the README as well. 

I hope you like it, sad but true my IDE has a different setup so my JS alignment is fairly messed up. But I took only the old logic without adding anything new.

### CODE REVIEW

**Comment by dohomi** [comment]
Trying to solve https://github.com/percolatestudio/publish-counts/issues/36

**Comment by dohomi** [comment]
@tmeasday it would be possible to merge both countFromField but not sure if its necessary. What do you think?

**Comment by tmeasday** [comment]
Hmm... I think `countFromField` should be for directly counting the field (which is what this PR does), and we be explicit if we are going to do anything else (like taking a length).

Is there any way to change the tab spacing? I'll need to reformat the commits otherwise

**Comment by dohomi** [comment]
I changed it now from 4 to 2, but still not sure if this is the right setup.

**Comment by tmeasday** [comment]
Ok, thanks @dohomi.

I refactored a little and possibly fixed some bugs along the way. @dburles can you please take look?

**Comment by dburles** [comment]
lgtm @tmeasday. Thanks @dohomi

**Comment by tmeasday** [comment]
Out in 0.4.0. Thanks @dohomi

**Pull request merged**
